### ISSUE TITLE
Is it mandatory to mention secretKeyRef in values yaml ?

### ISSUE THREAD

**Issue by MageshSrinivasulu** [sigstore/helm-charts#234]
```
cosign:
  secretKeyRef:
    name: ""
  cosignPub:  I have mentioned my public key here in base64 encoded format
```

Without mentioning secretKeyRef getting the below exception. But I am mentioning the public key in encoded format

Error from server (BadRequest): error when creating ".\\statefulset.yaml": admission webhook "policy.sigstore.dev" denied the request: validation failed: secret "" not found: spec.template.spec
