### ISSUE TITLE
validation timeouts and image digest fetch issues in AWS EKS and ECR

### ISSUE THREAD

**Issue by blazdivjak** [sigstore/helm-charts#249]
We publish and sign container images in AWS ECR using cosign and use latest version of [policy controller](https://github.com/sigstore/helm-charts/tree/main/charts/policy-controller) for validation.

We are running AWS EKS version `v1.22.9-eks-a64ea69` with nodes  `v1.22.6-eks-7d68063`.

Images are signed using AWS KMS keys and verified using public key stored in `ClusterImagePolicy`.

```yaml
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  annotations:
spec:
  authorities:
  - key:
      data: |
        -----BEGIN PUBLIC KEY-----
        ...
        -----END PUBLIC KEY-----
    name: authority-0
  images:
  - glob: '**'
```

When deploying large helm charts such as [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) we often get errors like:

```bash
Error: Internal error occurred: failed calling webhook "policy.sigstore.dev": Post "https://webhook.cosign-system.svc:443/validations?timeout=10s": context deadline exceeded
```

and issues with fetching digests:

```
invalid value: [<AWS_ACCOUNT_ID>.dkr.ecr.eu-north-1.amazonaws.com/prometheus/node-exporter:v1.3.1](http://<AWS_ACCOUNT_ID>.dkr.ecr.eu-north-1.amazonaws.com/prometheus/node-exporter:v1.3.1) must be an image digest: spec.containers[0].image
```

Both issues happen at random.

Some tests done:
- tried sha256 sum image pining
- tried publishing and signing just platform linux/amd64 container image to reduce size of digest
- tried scaling to multiple replicas and increasing cpu/memory limits for webhooks but didn't change a thing
- checked cloudwatch for performance issues and it looks ok
- tried running images manually with `kubectl run` and worked ok  

Any debugging tips much appreciated.
