### ISSUE TITLE
Rekor 1.0.0 release fails on trillian init containers

### ISSUE THREAD

**Issue by marcofranssen** [sigstore/helm-charts#376]
**Description**

When deploying the rekor 1.0.0 Helm chart it fails with following errors the following components:

trillian initContainers:
- logserver 
- logsigner

```bash
exec /bin/sh: exec format error
```

redis:

```bash
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

See below my values file.

```yaml
trillian:
  mysql:
    auth:
      username: sigstore-trillian
      password: TopSecretTest
      rootPassword: T0pS3cr3tT3st
```

**Version**

rekor 1.0.0 helm-chart
