### ISSUE TITLE
trillian chart does not deploy on Apple Silicon macs, but it could

### ISSUE THREAD

**Issue by federico-falconieri-form3** [sigstore/helm-charts#589]
The latest trillian chart does not deploy on apple silicon. As is, this is not exactly a bug but a conscious decision introduced in https://github.com/sigstore/helm-charts/pull/424 to address https://github.com/sigstore/helm-charts/issues/376.
But docker for mac on apple silicon macs can run amd64 images...

Solution: make the node scheduling optional

**Comment by federico-falconieri-form3** [comment]
apologies, this was already resolved by https://github.com/sigstore/helm-charts/issues/500. My issue is unrelated.

**Comment by federico-falconieri-form3** [comment]
Leaving this here, could be useful for others: to install the current version of the rekor chart (1.3.6) on an Apple Silicon mac it is sufficient to use this values file:

```yaml
trillian:
  logServer:
    nodeSelector:
      kubernetes.io/arch: arm64
  logSigner:
    nodeSelector:
      kubernetes.io/arch: arm64
```

Although I've resolved the problem on my specific situation, I'll leave it to the maintainers to decide if the issue should be closed or not...
