### ISSUE TITLE
Duplicate fields in policy-controller templates/webhook/deployment_webhook.yaml causing Flux v2 reconciliation failure

### ISSUE THREAD

**Issue by DonaldKellett** [sigstore/helm-charts#668]
## Summary

Duplicate fields in policy-controller `templates/webhook/deployment_webhook.yaml` causing Flux v2 reconciliation failure as shown in the screenshot below

![policy-controller-flux-failure](https://github.com/sigstore/helm-charts/assets/7777884/23cef739-ce15-4acf-9eed-d3c545ffef0f)

## Steps to reproduce

The issue appears with the default `policy-controller` Helm chart configuration since version `0.6.6`.

Run the following commands:

```bash
helm repo add sigstore https://sigstore.github.io/helm-charts
helm repo update
helm template \
    policy-controller \
    sigstore/policy-controller \
    --version 0.6.6 \
    --show-only templates/webhook/deployment_webhook.yaml | \
    yq '.spec.template.metadata.labels'
```

Output:

```yaml
app.kubernetes.io/name: policy-controller
app.kubernetes.io/instance: policy-controller
control-plane: policy-controller-webhook
helm.sh/chart: policy-controller-0.6.6
app.kubernetes.io/name: policy-controller
app.kubernetes.io/instance: policy-controller
app.kubernetes.io/version: "0.8.2"
app.kubernetes.io/managed-by: Helm
```

Notice the duplicated `app.kubernetes.io/name`, `app.kubernetes.io/instance` fields.

## Software version information

`sigstore/policy-controller` version `0.6.6` \(issue did not appear prior to `0.6.6`\)

- Kubernetes client version: `v1.28.3`
- Kubernetes server version: `v1.28.3+rke2r2` \(Rancher RKE2\)
- Helm version: `v3.13.2`
- Flux version: `2.1.2`
