### ISSUE TITLE
Request for tolerations, nodeSelector and affinity to be allowed to configure for all charts

### ISSUE THREAD

**Issue by Jaryllan** [sigstore/helm-charts#696]
Would like to request allowing tolerations, nodeSelector and affinity to be configured. Currently only trillian (logserver, logsigner, mysql) and rekor (redis, server) can be configured to add tolerations.

The following are the sample helm value used to configure the tolerations when install the scaffold chart

```
rekor:
  server:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  redis:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists

trillian:
  logServer:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  logSigner:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  mysql:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
```
